![Imgur](https://i.imgur.com/h4PPC71.png)
#Data Sayns va Sunʼiy Intellekt Praktikum
Maʼlumotlar tahlili. Pandas kutubxonasi.

9.21. Reytinglash.

In [ ]:
import numpy as np
import pandas as pd

Tartiblash (sort) va Reytinglash (rank)

In [ ]:
obj = pd.Series(range(4),index=['d','a','b','c'])

In [ ]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [ ]:
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv", index_col=0)
df.head()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left

In [ ]:
df.shape

(2499, 12)

In [ ]:
df.sort_index()

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,2899,ford,se,2011,clean vehicle,190552,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,25000,ford,door,2014,clean vehicle,64146,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [ ]:
df.sort_index(axis=1,inplace=True)

In [ ]:
df

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [ ]:
df.sort_index(axis=1,ascending=True)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
0,toyota,black,10 days left,usa,159348797,274117,cruiser,6300,new jersey,clean vehicle,jtezu11f88k007763,2008
1,ford,silver,6 days left,usa,166951262,190552,se,2899,tennessee,clean vehicle,2fmdk3gc4bbb02217,2011
2,dodge,silver,2 days left,usa,167655728,39590,mpv,5350,georgia,clean vehicle,3c4pdcgg5jt346413,2018
3,ford,blue,22 hours left,usa,167753855,64146,door,25000,virginia,clean vehicle,1ftfw1et4efc23745,2014
4,chevrolet,red,22 hours left,usa,167763266,6654,1500,27700,florida,clean vehicle,3gcpcrec2jg473991,2018
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,nissan,red,1 days left,usa,167722715,23609,versa,7800,california,clean vehicle,3n1cn7ap9kl880319,2019
2495,nissan,silver,21 hours left,usa,167762225,34553,versa,9200,florida,clean vehicle,3n1cn7ap5jl884088,2018
2496,nissan,silver,21 hours left,usa,167762226,31594,versa,9200,florida,clean vehicle,3n1cn7ap9jl884191,2018
2497,nissan,black,2 days left,usa,167762227,32557,versa,9200,florida,clean vehicle,3n1cn7ap3jl883263,2018
2498,nissan,silver,21 hours left,usa,167762228,31371,versa,9200,florida,clean vehicle,3n1cn7ap4jl884311,2018

In [ ]:
df.sort_values(by='price', ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
318,chevrolet,black,18 hours left,usa,167418694,117059,door,0,colorado,salvage insurance,kl1td66e39b645208,2009
305,ford,gold,8 days left,usa,167610324,246065,door,0,kansas,salvage insurance,1fafp55u03a242094,2003
510,ford,silver,17 hours left,usa,167357806,86841,door,0,oklahoma,salvage insurance,3fahp0ga3ar366961,2010
522,ford,red,17 hours left,usa,167357813,145483,door,0,oklahoma,salvage insurance,1fmcu03128kc80487,2008
144,dodge,silver,2 days left,usa,167756167,123660,door,0,utah,salvage insurance,1c3cdzab0en111068,2014

In [ ]:
df.sort_values(by=['price','mileage'], ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
502,mercedes-benz,silver,2 days left,usa,167607883,25302,sl-class,84900,florida,clean vehicle,wddjk7ea3hf044968,2017
1340,ford,no_color,2 days left,usa,167780682,10536,drw,74000,illinois,clean vehicle,1ft8w4dt6ked32656,2019
1336,ford,no_color,2 days left,usa,167780680,9643,drw,70000,illinois,clean vehicle,1ft8w3dt3kee48276,2019
277,dodge,blue,21 hours left,usa,167759490,10944,challenger,67000,ohio,clean vehicle,2c3cdzl97kh518237,2019
1215,ford,black,21 hours left,usa,167718954,6500,srw,65500,indiana,clean vehicle,1ft7w2bt0kec44818,2019
...,...,...,...,...,...,...,...,...,...,...,...,...
196,ford,white,2 days left,usa,167656523,76858,mpv,0,texas,clean vehicle,1fbax2cv0hkb32599,2017
349,heartland,white,7 days left,usa,167266321,1,sundance,0,pennsylvania,clean vehicle,5sfgf29269e031344,2009
309,chevrolet,maroon,18 hours left,usa,167418651,0,door,0,wyoming,salvage insurance,3gnek12t74g240524,2004
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993

In [ ]:
df.sort_values(by='year', ascending=False)

,brand,color,condition,country,lot,mileage,model,price,state,title_status,vin,year
2306,nissan,black,7 hours left,usa,167129224,264,cargo,19000,california,clean vehicle,3n6cm0kn9lk693851,2020
2305,nissan,gray,2 days left,usa,167743353,15387,rogue,14700,pennsylvania,clean vehicle,knmat2mv5lp500471,2020
2302,nissan,silver,21 hours left,usa,167725016,19597,rogue,21100,south carolina,clean vehicle,5n1at2mt6lc714032,2020
657,chevrolet,gray,21 hours left,usa,167781406,179,trax,22000,california,clean vehicle,3gncjksbxll181398,2020
1217,ford,silver,21 hours left,usa,167722215,5920,explorer,32500,missouri,clean vehicle,1fmsk8dh2lga15480,2020
...,...,...,...,...,...,...,...,...,...,...,...,...
322,ford,green,19 hours left,usa,167359174,0,chassis,0,california,salvage insurance,1fdee14n7rha47894,1994
362,ford,white,2 days left,usa,167361489,206162,pickup,25,georgia,salvage insurance,1ftdf15y2rnb12612,1994
545,gmc,light blue,18 hours left,usa,167358601,0,door,0,colorado,salvage insurance,1gkfk16k5pj701631,1993
405,ford,white,17 hours left,usa,167611661,41577,door,25,arkansas,salvage insurance,2ftcf15y9eca14589,1984
32,chevrolet,red,22 hours left,usa,167763370,46226,camaro,29800,pennsylvania,clean vehicle,1q87t3n166389,1973